### ISSUE TITLE
Feature Request: Contributors list in the about section

### ISSUE THREAD

**Issue by mnamegaurav** [hamhaingaurav/devresources#20]
Show at least top 5 contributors in the bottom of about section, each person should be shown as a rounded circle hyperlink to his/her GitHub profile.

At the end if top 5 contributors icon, put of a link to `show all` contributors, which would  redirect to the contributors list page of this project.

**Comment by Striver08** [comment]
I would like to work on this issue.

**Comment by mnamegaurav** [comment]
> I would like to work on this issue.

Yes, Why not, start working on it.

**Comment by mnamegaurav** [comment]
There is no need of it, as everything is on official repo of this project. Thanks
