### ISSUE TITLE
Feature Request : Add Heading to tags!

### ISSUE THREAD

**Issue by rahulnegi20** [hamhaingaurav/devresources#26]
Giving Heading to Tags under resource section might be helpful to newcomers to understand the UI.

P.S : I can add this functionality!

**Comment by mnamegaurav** [comment]
Can you elaborate it a bit, what kind of heading and where ?

**Comment by rahulnegi20** [comment]
![IMG_20210317_095333](https://user-images.githubusercontent.com/36270407/111414847-c0417180-8706-11eb-8d46-8ebc41fb0e79.jpg)

I tried explaining here with this edited image!

**Comment by mnamegaurav** [comment]
Hey @rahulnegi20 , that is self understandable, it is the part of UX, no need of adding a heading. Thanks for the suggestion, looking forward to more from you.
