### ISSUE TITLE
Setup GitHub pipeline for automated tests

### ISSUE THREAD

**Issue by anoop1409** [hamhaingaurav/devresources#28]
The project is missing **unit tests** and also the **pipeline** to execute those in the cloud.
It is important to have unit tests to cover the critical parts and logic of the project and make them execute automatically with every push/merge.

**Comment by anoop1409** [comment]
I would like to work on this and as a first step, already created a Pull request with the initial set of tests.
Will also look at the pipeline in GitHub for automated test execution.

**Comment by mnamegaurav** [comment]
Sure, that would be great.

**Comment by anoop1409** [comment]
Created this PR - #31

**Comment by mnamegaurav** [comment]
Please resolve the comments on the PR, #31
