### ISSUE TITLE
Design issue in password field on signup page

### ISSUE THREAD

**Issue by codecrook** [hamhaingaurav/devresources#34]
Password field on signup page looks okay in small screens.
<img width="1440" alt="Screenshot 2021-03-26 at 1 06 20 PM" src="https://user-images.githubusercontent.com/14542991/112599771-5deb1e00-8e36-11eb-84a0-3ba282b04f51.png">

But breaks for large-screen.
<img width="1440" alt="Screenshot 2021-03-26 at 1 25 39 PM" src="https://user-images.githubusercontent.com/14542991/112600197-e4076480-8e36-11eb-9fba-bc98a7e016ab.png">

**Comment by rahulnegi20** [comment]
What's your resolution? @codecrook 
i have 1366*768 and it is working fine though.

**Comment by codecrook** [comment]
Oh. Mine is 2560*1600 and as you can see the screenshots above, it's breaking.

**Comment by mnamegaurav** [comment]
This issue has been fixed by @rahulnegi20 , Thanks Guys.
